### ISSUE TITLE
[Rogue][Sap applies poison]

### ISSUE THREAD

**Issue by Mofoleone** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4947] opened 2015-01-29 21:46 UTC
When you use sap and have crippling poison on weapons, it is applied to the target.

**Comment by Nzzoth** [comment] 2015-01-29 22:00
Hello Mofoleone, this is not a bug but a blizzlike feature we recently added in patch 10.2 which you can read on our forums www.wow-one.com .
Issue closed as it is not a bug.

**Closed by Nzzoth** 2015-01-29 22:00 UTC

**Comment by FeenixDrakon** [comment] 2015-05-10 18:40
As a retail rogue during Vanilla/TBC, I can confirm that Sap did NOT apply poisons!
