### ISSUE TITLE
[Quest]:The Missing Diplomat

### ISSUE THREAD

**Issue by wolkodlak** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5099] opened 2015-02-17 15:05 UTC
Hi.
I was trying to complete chain-quest "The Missing Diplomat" in Menethil harbor several times. Each time I get NPC Slim down to 10-25% I complete first part of quest and he becomes friendly and escapes. It leaves me with second part of quest incomplete.

Link to database of the quest: http://www.wow-one.com/database/index.php?quest=1249
NPC Slim: http://www.wow-one.com/database/index.php?npc=4962
Quest starter NPC: http://www.wow-one.com/database/index.php?npc=4963#starts

I love this chain and I hope you can fix this.
Regards,
Wolkodlak

**Comment by Nzzoth** [comment] 2015-02-17 20:52
Duplicate of #234 

**Issue closed**

**Closed by Nzzoth** 2015-02-17 20:52 UTC
