### ISSUE TITLE
[PRIEST] [SPELL] Mindcontrol Bug

### ISSUE THREAD

**Issue by lokol99** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4315] opened 2014-05-15 13:26 UTC
Edit : Removed to prevent abuse, thank you for the report.

http://www.wow-one.com/forum/topic/79058-mind-control-issue/

**Comment by Nain1** [comment] 2015-01-28 21:34
bump

**Comment by Nain1** [comment] 2015-01-29 00:12
This is still crashing the server quite often.

**Comment by ender-feenix** [comment] 2015-01-29 01:29
There was a miss-communication about how the fix for this was supposed to work.  It has since been tested and confirmed by @Nzzoth .

**Comment by Nzzoth** [comment] 2015-01-29 01:33
Hello, as Ender stated there was some miscommunication. The following issue is tested and confirmed on PTR.

**Comment by ender-feenix** [comment] 2015-02-03 03:40
After some internal cleanups, this needs to be re-tested on the PTR.

**Comment by Kaiitothewai** [comment] 2015-02-03 14:25
**Fix is Confirmed on PTR**

**Comment by Kaiitothewai** [comment] 2015-02-05 17:42
Live.

**Closed by Kaiitothewai** 2015-02-05 17:42 UTC
Labels: Class.Priest, Core.Spells, Dev.OnPTR
