### ISSUE TITLE
[Hunter][Item] T1 3 piece set bonus range doesn't work

### ISSUE THREAD

**Issue by tevir** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5131] opened 2015-02-27 18:28 UTC
the 3 piece hunter set bonus to increase the range of mend pet from 20 to 30 yds, increase effect by 10% and reduce mana by 30%. Although the mana reduction and effect bonus work the most important part the range is not applied at all. This bonus in my opinion is probably the best pvp set bonus hunters can get since many times, especially when fighting mages your pet will get CC'd when it is over 20 yds from you since your max range is 41. That 10 yds on pet dispel is huge.

http://www.wow-one.com/database/index.php?itemset=206

**Comment by Nzzoth** [comment] 2015-02-27 18:52
#2661
Closed due to being a duplicate of the above said issue.

Kind regards, Nzzoth.

**Closed by Nzzoth** 2015-02-27 18:52 UTC
