### ISSUE TITLE
[Spell Fear/Psychic Scream] [Targets attack/Cast spells under effect]

### ISSUE THREAD

**Issue by Mofoleone** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4276] opened 2014-04-26 16:43 UTC
Players and NPCs while under fear spell they "sometimes" can attack and cast spell totally ignoring that they are under fear effect.
Why I wrote "sometimes" because it doesn't happen every time.

**Comment by devidao** [comment] 2015-04-21 08:51
Can not reproduce this

**Comment by Nzzoth** [comment] 2015-04-21 09:29
A fix for this has been live for some time, if somebody encounters it please post here.
Closed.

**Closed by Nzzoth** 2015-04-21 09:29 UTC
Labels: Class.Priest, Class.Warlock, Core.Combat

**Comment by Cabro** [comment] 2015-04-21 10:49
Is the fix viable only for fear effects or for flees too?

**Comment by Nzzoth** [comment] 2015-04-21 15:31
It is for all crowd effects that behaved that way. This was fixed when KT was released.

**Comment by Cabro** [comment] 2015-04-22 17:35
So only for fears. Because for flees they still attack/cast spells.

**Comment by Nzzoth** [comment] 2015-04-22 22:12
Make a seperate issue about it read the title that is a different issue what you described.

Kind regards.
