### ISSUE TITLE
AQ Twin Emps on Emerald Dream Server: Teleport Bug

### ISSUE THREAD

**Issue by Vivia100** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#5197] opened 2015-04-19 22:45 UTC
On the Emerald Dream server, the Twin Emperor teleport is bugged.

We believe that if any damage over time(dots) exist on them or if they are too far away from each other or if the main tanks have any heal over times (hots) on them or if a warrior charges one of the emperors that the teleport will bug and will bring the 2 emperors together causing them to heal each other to full health and kill one side of the room. We have tried all these strategies and even so, the fight will work for a certain period of time (For example we got them down to 51%) but will eventually bug out anyways and they will teleport on top of each other and heal. Even the guilds that have actually gotten Twin Emps down took about 5-15 tries just to get them down and they claim to the rest of the guilds that you have to be "lucky".. 

This fight hasn't even become a matter of strategy and gear anymore but instead a matter of "luck".. I feel like it should be a top priority to be fixed as soon as possible! 

I also saw an issue tracker post and heard from some former Warsong Players on the ED server that this issue existed on the Warsong server awhile back and was fixed as well. I hope it is an easy to correct.

**Comment by Vivia100** [comment] 2015-04-20 01:12
Also, I guess a tank dying also causes the bug..

**Comment by Vivia100** [comment] 2015-04-20 01:13
Too much distance between bosses can cause it? Maybe...

**Comment by Vivia100** [comment] 2015-04-20 01:14
Also... Vek'lor always seems to teleport to Vek'nilash.

**Comment by Vivia100** [comment] 2015-04-20 01:23
Also realize that there is a previous post of this for the Warsong server, but we may have different issues than they had..

**Comment by Mofoleone** [comment] 2015-04-22 09:22
#3857 
Close

**Comment by Nzzoth** [comment] 2015-04-22 09:25
Closed due to being a duplicate of #3857 .

**Closed by Nzzoth** 2015-04-22 09:25 UTC
