### ISSUE TITLE
[BG] [WSG] Flag Capture issue

### ISSUE THREAD

**Issue by darth-zeke** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#4199] opened 2014-03-08 04:48 UTC
If you are standing on the flag cap point when the flag is returned, it won't cap the flag.  It should cap the flag the instant it is returned; allowing no time for it to be picked up if you are standing on the cap point.  Instead, it makes it near impossible to cap the flag when alliance are in your base because you have to move into the cap point  (while slowed most of the time)  whereas alliance merely have to click the flag to grab the flag first.

**Comment by ender-feenix** [comment] 2015-02-03 03:38
The fix for this issue was reverted in September due to it causing some issues.  Those issues have since been fixed.  Therefore this needs to be re-tested.  The fix is on the PTR as of now.

**Comment by Nzzoth** [comment] 2015-02-11 00:22
**Fix confirmed on PTR**

**Comment by Kaiitothewai** [comment] 2015-02-24 11:39
**Live with Patch 10.10**

**Closed by Kaiitothewai** 2015-02-24 11:39 UTC
Labels: Core.Battlegrounds, Dev.OnPTR, Report.FixConfirmed
