### ISSUE TITLE
[QUEST][DM] Unfinished Gordok Business

### ISSUE THREAD

**Issue by warchieflj** [FeenixServerProject/Phoenix_1.12.1_Issue_tracker#32] opened 2016-07-02 22:54 UTC
Unable to find the Prince's chest which contains [Gauntlet of Gordok Might].The chest is supposed to be near the Prince in DM library
link for the quest item http://www.wow-one.com/database/?object=179545

**Comment by Kaiitothewai** [comment] 2016-07-14 16:14
This is sort of a duplicate of #26 afaik

**Comment by devastator** [comment] 2016-07-18 09:33
https://github.com/FeenixServerProject/Phoenix_1.12.1_Issue_tracker/issues/26

**Closed as completed by devastator** 2016-07-18 09:33 UTC
